# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_name', models.BooleanField(default=False)),
                ('room_number', models.IntegerField(default=0)),
            ],
        ),
    ]
