# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(choices=[('LT', 'Light'), ('Fan', 'Fan')], max_length=20),
        ),
    ]
