# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20170527_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(choices=[('LT', 'Light'), ('FN', 'Fan')], max_length=20),
        ),
    ]
